### ISSUE TITLE
Unable to find setup_elliot.R

### ISSUE THREAD

**Issue by Raju06** [elliottmorris/world-cup-2018#1]
I am lucky to learn the approach. I request you to upload setup_elliot.R so that I could learn the way you approach in visualization. Please help me learn your way.

**Comment by elliottmorris** [comment]
Hi Raju,

I don't typically upload my setup files, but might consider it this time when updating the scripts to work with the knockout rounds. Will close this issue for now.

**Comment by Raju06** [comment]
Hi Elliott,

Thank you for considering it for this time. It will surely be a great help.
